# docker-compose.yml

version: '3'

services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: ./resources/utils/dockerfiles/flask.Dockerfile
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks: 
      - appnet
      
  nginx:    
    image: rproxy-nginx
    build:
      context: .
      dockerfile: ./resources/utils/dockerfiles/nginx.Dockerfile
    ports:
      - "8989:80"
    depends_on:
      - flask
    networks: 
      - appnet
    
  mysql:
    image: db-mysql
    restart: on-failure
    build:
      context: .
      dockerfile: ./resources/utils/dockerfiles/mysql.Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rpass
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=appusr
      - MYSQL_PASSWORD=apppass
    volumes:
      - mysqldata:/var/lib/mysql
    networks: 
      - appnet
    
  pushpin:
    image: sse-pushpin
    build:
      context: .
      dockerfile: ./resources/utils/dockerfiles/pushpin.Dockerfile
    ports:
      - "7999:7999"
      - "5560:5560"
      - "5561:5561"
      - "5562:5562"
      - "5563:5563"
    environment:
      - VAR=val
    depends_on:
      - nginx
      - flask
    networks: 
      - appnet

volumes:
  mysqldata:
    external: false

networks: 
  appnet:
    driver: bridge
